name: posbinduptm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  dotted_border: ^2.1.0
  equatable: ^2.0.7
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_datetime_picker_plus: ^2.2.0
  fpdart: ^1.1.1
  get_it: ^8.0.3
  hive: ^4.0.0-dev.2
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.20.2
  isar_flutter_libs: ^4.0.0-dev.14
  path_provider: ^2.1.0
  supabase_flutter: ^2.8.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
